version: '2'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=olx_uz_flat_scrapper
      - POSTGRES_USER=belnarto
      - POSTGRES_PASSWORD=passw0rd