server:
  error:
    include-message: always

spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/olx_uz_flat_scrapper}
    username: ${POSTGRES_USER:belnarto}
    password: ${POSTGRES_PASSWORD:passw0rd}
  flyway:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/olx_uz_flat_scrapper}
    user: ${DB_MIGRATION_USER:belnarto}
    password: ${DB_MIGRATION_PASSWORD:passw0rd}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          lob.non_contextual_creation: true
        connection.autocommit: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    banner_mode: "OFF"